name: Spec Check Filter Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: kube-kaptain/buildon-github-actions/.github/workflows/spec-check-filter-release.yaml@1.1.19
    permissions:
      contents: write
      packages: write
      checks: write
